### ISSUE TITLE
Deployment to Heroku

### ISSUE THREAD

**Issue by dionysiaA** [kriasoft/nodejs-api-starter#32]
Not clear how to deploy an app to heroku, we've tried this **node tools/publish <host>       # where <host> is the name of your web server (see ~/.ssh/config)** but we are not quite sure what the host name is for a heroku app. Could you please guide us?
 
The steps followed were to pass an IP obtained from running this **ssh -v git@heroku.com** as well as the name of the app.

**Comment by koistya** [comment]
@dionysiaA you can only push the "api" (Node.js app) to Heroku (as far as I understand, it doesn't allow you to deploy Nginx, Redis as Docker containers). Anyhow, in order to build the "api" service you can run:

```bash
$ docker-compose run --rm api /bin/sh -c "yarn install; yarn run build"
```

This will compile the project into the `build` folder (alternatively you can run `yarn install; yarn run build`). Then in order to build the "api" Docker image and push it to Heroku, you would run:

```bash
$ heroku container:push web
```

You can find more information [here](https://devcenter.heroku.com/articles/container-registry-and-runtime).

But, I would rather use either [DigitalOcean](https://m.do.co/c/eef302dbae9f) or Amazon AWS which would allow you to run Docker Compose on the remote server and deploy the whole thing at once - Node.js API + Nginx + Redis + Postgres, that's where the `tools/publish.js` script could be handy.
