### ISSUE TITLE
Instructions on hooking up to react-starter-kit

### ISSUE THREAD

**Issue by pruhstal** [kriasoft/nodejs-api-starter#39]
Hi there,

I recently cloned react-starter-kit from kriasoft and already started to build out my front-end with it. One thing I'd really love to do is use this nodejs-api-starter to communicate with the react-starter-kit, although I'm unsure of where to go. Most likely I'd need to modify the nginx proxy_pass, but need a little push in the right direction.

For now my workflow looks like: `yarn start` on react-starter-kit in one tab, and then `docker-compose up -d` in another tab which starts the API server.

My goal is to be able to build out all my REST endpoints on with the nodejs-api-starter and have my client talk to the react-starter-kit.

FWIW, I'm running react-starter-kit on port 3001 and the nodejs-api-starter runs on 8080.

**Comment by tim-soft** [comment]
This and RSK could pair together really nicely, I could see how a lot of people would want to keep the backend separate.

Is their a "Good Way" to swap the RSK backend to connect to this boilerplate? Maybe this isn't the right place to ask but definitely wanted to express interest with a bump.

**Comment by pruhstal** [comment]
@tim-soft Ideally, I'd like to have the node.js api starter kit powering my react starter kit (e.g. this repo).

Then I'd have maybe 3 servers:
> 1 API (https://github.com/kriasoft/nodejs-api-starter)
> 1 Client (https://github.com/kriasoft/react-starter-kit)
> 1 DB server (that proxies over to my API server)

**Comment by tim-soft** [comment]
I am actually working towards a very similar setup and use reverse-proxies via nginx

Here's a link that might help give you some more direction, although RSK has changed a lot since this PR

[Remove data API endpoint from the boilerplate #1057](https://github.com/kriasoft/react-starter-kit/pull/1057)

**Comment by pruhstal** [comment]
@tim-soft Awesome! Have you gotten that far at this point? I'd be curious to see how you're linking everything together.

**Comment by cmmartin** [comment]
If you are running two separate servers for each project, you can easily communicate between these two projects over HTTP. Just send HTTP requests from the `react-starter-kit` client/server to this api running on another machine/port.

I wouldn't necessarily recommend that though, because the two projects have a lot of overlap. They both handle authentication and they both run a `graphql` server. That's a lot of redundancy. I would use one or the other. Basically, `react-starter-kit` is a full stack example and this is just a backend. 

You can easily modify this project to also serve your front-end though. Just serve your front-end  [here](https://github.com/kriasoft/nodejs-api-starter/blob/master/src/app.js). I'm doing something like this...

```javascript
app.use('/assets', express.static(path.resolve(__dirname, '../assets')))

app.get('/', (req, res) => {
  res.send(`
  <!DOCTYPE html>
  <html>
    <head>
        <title>My API Starter Client</title>
    </head>
    <body>
      <div id="root"></div>
    </body>
    <script>
      window.__APP_INITIAL_STATE__ = ${JSON.stringify(initialState)}
    </script>
    <script src="/assets/bundle.min.js"></script>
  </html>
  `)
})
```

Then you can generate your `bundle.min.js` file however you wish and place it in the `/assets` folder.

**Comment by koistya** [comment]
1. Install `http-proxy-middleware` package in your CRA app project
2. Create `src/setupProxy.js` file in the CRA project with the following contents:

```js
const proxy = require('http-proxy-middleware');

module.exports = function(app) {
  app.use(
    '/graphql',
    proxy({
      target: 'http://localhost:8080',
      changeOrigin: true,
      router: {
        'test.127.0.0.1.xip.io:3000': 'https://test.example.com',
        'prod.127.0.0.1.xip.io:3000': 'https://example.com',
      },
    }),
  );
};
```
