### ISSUE TITLE
no entry file inside docker image

### ISSUE THREAD

**Issue by EclipticWld** [kriasoft/nodejs-api-starter#66]
Docker can't find server.js file inside the image. The way to reproduce:

```bash
$ node tools/publish.js foobar
$ docker run -p 8080:8080 api
```
response:
```bash
Error: Cannot find module '/usr/src/app/build/server.js'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:453:25)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
```

**Comment by koistya** [comment]
Try running this:

```bash
$ docker-compose run --rm --no-deps api yarn        # Install Node.js dependencies
$ docker-compose run --rm --no-deps api yarn build  # Build the project into ./build
$ docker build --no-cache --tag api .               # Build the production "api" image
$ docker run -p 8080:8080 api                       # Check it works
````

**Comment by koistya** [comment]
@EclipticWld the current setup expects you to build the app first, then run `docker build` command that copies all the compiled output into the image (`COPY . .`), see `Dockerfile`. It is possible though to tweak `Dockerfile` so that it would build the app during image compilation and then prune non-production dependencies. Please, let me know if the later workflow works better for you.

**Comment by EclipticWld** [comment]
Thank you @koistya! That was helpful to move forward.
