### ISSUE TITLE
Tutorial request

### ISSUE THREAD

**Issue by Smmaca** [kriasoft/nodejs-api-starter#68]
I'd really like to see a nice tutorial explaining how to build this starter from scratch. A starter is all very well until you need to modify it and have no idea why anything was done in the way it was done.

Obviously this is a huge ask but I wanted to put it out there in case there was someone who both could and wants to do this.

**Comment by DaveyEdwards** [comment]
What sort of tutorials around this project would you like to see if it wasn't the FULL project or most important parts to start with?  

I personally have been thinking about:

- Hooking up:
  - Cloud providers such as Google Cloud Platform or AWS
  - Error handeling
  - Storage buckets
  - Databases (NoSQL, SQL, GraphDBs)
  - Frontends such as koistyas https://github.com/kriasoft/react-static-boilerplate
- Adding types to the schema
- Security risks of your application
- Real tutorials for deploying a application to the public
  - How to monitor that application
- Writing database queries
- 10,000 foot view of implementing something on the front or backend and see how it effects everything all the way through

Would love to hear what others are the most unsure about

**Comment by priedthirdeye** [comment]
+1 for 10,000 foot view and/or a getting started

I'm pretty proficient in node, docker, modern javascript and other technologies in this stack, but Im new to graphql and react. 

Someone like me spins up this starter and says "now what?" I look to the docs and there doesn't appear to be any past set up. I look to the code comments and there aren't any. 

A 10,000 foot view / getting started could include:

- General 
How will this ultimately interact with a front-end. Bridging the authentication from front end to back end, etc. 
- Your first migration. 
Insert a story and comment
- Add your own data type, migration, and seed
Categories for stories? Tags for stories? Completely new top level data type (such as a product)?

These are just a few ideas. I wouldn't expect documentation on the intricacies of GraphQl, React and Relay since there are already docs for that. I'm interested in a getting started to build up *this* starter. There would inevitabily be some overlap into those other technologies, but that shouldn't be the focus.

**Comment by koistya** [comment]
I just started writing a tutorial here -> https://graphqlstart.com
